#server
server:
  port: 80
#  context-path: /
#  tomcat:
#    uri-encoding: utf-8

#mybatis
#mybatis:config-location:classpath:mybatis-config:xml
#mybatis:mapper-locations:classpath:**/mapper/*/*:xml

##master \u00CA\u00FD\u00BE\u00DD\u00D4\u00B4\u00C5\u00E4\u00D6\u00C3
#master:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: root
#    driverClassName: com.mysql.jdbc.Driver
#
## cluster \u00CA\u00FD\u00BE\u00DD\u00D4\u00B4\u00C5\u00E4\u00D6\u00C3
#cluster:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: root
#    driverClassName: com.mysql.jdbc.Driver

#sharding.jdbc.datasource:
#    names: ds_master,ds_slave_0
#    ds_master_0:
#      type: org.apache.tomcat.jdbc.pool.DataSource
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8
#      username: root
#      password: root
#    ds_master_0_slave_0:
#      type: org.apache.tomcat.jdbc.pool.DataSource
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf-8
#      username: root
#      password: root
##      ds_slave_1:
##        type: org.apache.tomcat.jdbc.pool.DataSource
##        driver-class-name: com.mysql.cj.jdbc.Driver
##        url: jdbc:mysql://172.16.93.24:3306/mybatis_plus_1?useSSL=false
##        username: root
##        password: 123456
#    config:
#      masterslave:
#        load-balance-algorithm-type: round_robin
#        name: ds_ms
#        master-data-source-name: ds_master_0
#        slave-data-source-names: ds_master_0_slave_0
#mybatis-plus:
#  typeAliasesPackage: com.example.springbootmutidatasourcemybatisplus.entity
#  mapperLocations: classpath:/mapper/*.xml
#  typeEnumsPackage: com.baomidou.springboot.entity.enums
#  configuration:
#    call-setters-on-nulls: true
#    map-underscore-to-camel-case: true
#  global-config:
#    id-type: 0
#    logic-delete-value: 2
#    logic-not-delete-value: 1
#    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
#  type-enums-package: com.baomihua.demo.enums
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/test1?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #\u5B9E\u4F53\u626B\u63CF\uFF0C\u591A\u4E2Apackage\u7528\u9017\u53F7\u6216\u8005\u5206\u53F7\u5206\u9694
  typeAliasesPackage: org.lin.example.springbootdruidmutidatasourcemybatisplus.entity
  global-config:
    #\u4E3B\u952E\u7C7B\u578B  0:"\u6570\u636E\u5E93ID\u81EA\u589E", 1:"\u7528\u6237\u8F93\u5165ID",2:"\u5168\u5C40\u552F\u4E00ID (\u6570\u5B57\u7C7B\u578B\u552F\u4E00ID)", 3:"\u5168\u5C40\u552F\u4E00ID UUID";
    id-type: 2
    #\u5B57\u6BB5\u7B56\u7565 0:"\u5FFD\u7565\u5224\u65AD",1:"\u975E NULL \u5224\u65AD"),2:"\u975E\u7A7A\u5224\u65AD"
    field-strategy: 2
    #\u9A7C\u5CF0\u4E0B\u5212\u7EBF\u8F6C\u6362
    db-column-underline: true
    #\u5237\u65B0mapper \u8C03\u8BD5\u795E\u5668
    refresh-mapper: true
    #\u6570\u636E\u5E93\u5927\u5199\u4E0B\u5212\u7EBF\u8F6C\u6362
    #capital-mode: true
    #\u5E8F\u5217\u63A5\u53E3\u5B9E\u73B0\u7C7B\u914D\u7F6E,\u4E0D\u5728\u63A8\u8350\u4F7F\u7528\u6B64\u65B9\u5F0F\u8FDB\u884C\u914D\u7F6E,\u8BF7\u4F7F\u7528\u81EA\u5B9A\u4E49bean\u6CE8\u5165
    key-generator: com.baomidou.mybatisplus.incrementer.H2KeyGenerator
    #\u903B\u8F91\u5220\u9664\u914D\u7F6E\uFF08\u4E0B\u97623\u4E2A\u914D\u7F6E\uFF09
    logic-delete-value: 0
    logic-not-delete-value: 1
    #\u81EA\u5B9A\u4E49sql\u6CE8\u5165\u5668,\u4E0D\u5728\u63A8\u8350\u4F7F\u7528\u6B64\u65B9\u5F0F\u8FDB\u884C\u914D\u7F6E,\u8BF7\u4F7F\u7528\u81EA\u5B9A\u4E49bean\u6CE8\u5165
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #\u81EA\u5B9A\u4E49\u586B\u5145\u7B56\u7565\u63A5\u53E3\u5B9E\u73B0,\u4E0D\u5728\u63A8\u8350\u4F7F\u7528\u6B64\u65B9\u5F0F\u8FDB\u884C\u914D\u7F6E,\u8BF7\u4F7F\u7528\u81EA\u5B9A\u4E49bean\u6CE8\u5165
#    meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
    #\u81EA\u5B9A\u4E49SQL\u6CE8\u5165\u5668
    #sql-injector: com.baomidou.springboot.xxx
    # SQL \u89E3\u6790\u7F13\u5B58\uFF0C\u5F00\u542F\u540E\u591A\u79DF\u6237 @SqlParser \u6CE8\u89E3\u751F\u6548
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false